### ISSUE TITLE
Change Enter Full Screen to Exit Full Screen once in full screen mode

### ISSUE THREAD

**Issue by tkoolen** [RobotLocomotion/director#183]
Just a tiny thing.

By the way, the updated version of director that comes with drake now is amazing!

**Comment by patmarion** [comment]
I think this might be a feature of your window manager, not a feature provided by the app?  Can you show a screenshot?

**Comment by tkoolen** [comment]
I don't care enough about this to investigate further :-) Sorry to bother you.
