### ISSUE TITLE
Screen Grabber returns unexpected error message

### ISSUE THREAD

**Issue by vtjeng** [RobotLocomotion/director#192]
When I click the "Save Screenshot" button on the Screen Grabber Panel generated by `director.screengrabberpanel.ScreenGrabberPanel(view)`, the following error message appears.

```
Traceback (most recent call last):
  File "/home/vtjeng/director/build/install/lib/python2.7/dist-packages/director/screengrabberpanel.py", line 124, in onSaveScreenshot
    app.getMainWindow().statusBar().showMessage('Saved: ' + filename, 2000)
AttributeError: 'NoneType' object has no attribute 'statusBar'
```

This seems to be a reproducible error.

**Comment by patmarion** [comment]
Thanks for the report.  I think it still saves screenshots, despite the error?

**Comment by vtjeng** [comment]
Yes, I can confirm that it still saves screenshots.

**Comment by patmarion** [comment]
this has been fixed.
