### ISSUE TITLE
Add Joint Frame Visualization?

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/director#210]
Can joint frames be visualized in Director / Drake Visualizer? Here's an example of what it looks like in Gazebo:

![screenshot from 2016-03-07 10 05 21](https://cloud.githubusercontent.com/assets/1388098/13574857/04d72bc4-e454-11e5-8696-d0356d2c8996.png)

**Comment by patmarion** [comment]
No, not currently.  The visualizer doesn't receive kinematic tree information from drake, so it does not have access to this information.  If we want to add this feature, we could open a new issue under drake to expand the rigid body tree drawing commands to provide the visualizer with the kinematic information.

The visualizer does draw the link frame for each body, which is often in line with the joint frame.  You can open the object model (press F1 or use the View menu) and then expand the tree to explore the bodies and frames.

**Comment by liangfok** [comment]
Thanks for the quick reply. The ability to visualize joint frames is sufficient for now.

**Comment by patmarion** [comment]
By the way, you can right-click on a body in the 3D view to open a context menu.  From the menu, pick "select" and that will expand the object model automatically to the selected object.  You can also double click an object to show/activate its frame.  Double click again to deactivate.
