### ISSUE TITLE
README link to documentation Broken

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/director#266]
In the [Documentation](https://github.com/RobotLocomotion/director/blob/master/README.rst#documentation) section of README.rst, the link to online help is broken. It's currently pointing to:

https://github.com/RobotLocomotion/director/blob/master/tree/master/docs/director/README.md

**Comment by wxmerkt** [comment]
GitHub changed their URL scheme, but we've also deprecated this Markdown README (cf. #120, #121).  I've updated the link to reflect - cf. https://github.com/RobotLocomotion/director/pull/267
