### ISSUE TITLE
Update Superbuild to Not Default to USE_SYSTEM_VTK=ON

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/director#311]
`Director`'s superbuild should check if `vtk5` is installed on the system before it decides to use `USE_SYSTEM_VTK=ON`. If `vtk5` is _not_ installed, `Director` should use `USE_SYSTEM_VTK=OFF`.

This was originally mentioned here: https://github.com/RobotLocomotion/drake/issues/2624#issuecomment-251938584

**Comment by liangfok** [comment]
@patmarion, I'd like to assign this ticket to myself but can't. Can I get the bits?

**Comment by patmarion** [comment]
Even though I made the comment I'm not sure I want the feature.  I don't always like top level options that automatically set based on the environment.  I usually prefer default options to be predictable.

But there should definitely be a mechanism in place to catch the issue at configure time.  In your case, director found vtk6 and succeeded to configure, but it should have been an error.  If vtk isn't installed at all, then the issue will be caught at configure time, im fine with that.

**Comment by liangfok** [comment]
OK I'll look into updating the super-build system to by default verify at configure time whether `vtk5` is installed on the system, and to error out if it is not.

**Comment by patmarion** [comment]
I'll close this one now.  Sounds like the logic will be added to drake's superbuild, not director's.
