### ISSUE TITLE
Camera Control "track modes" no longer do tracking in drake-visualizer

### ISSUE THREAD

**Issue by maddog-tri** [RobotLocomotion/director#378]
Activating a "Track Mode" via the Camera Control Panel in drake-visualizer doesn't quite work any more. It seems like the state of target is grabbed at the moment that the target is selected, and never updated after that.

I am pretty positive that this regression is a side-effect of the changes in #362.

**Comment by patmarion** [comment]
yes it is.  I'll make a fix tomorrow, thanks!

**Comment by patmarion** [comment]
in the meantime, if its blocking, you can cd to externals/director and revert commit 1570241

**Comment by mauricefallon** [comment]
+1 I had noticed that too

**Comment by patmarion** [comment]
just to confirm, @mauricefallon this bug is specific to the drake-visualizer app, is that what you are using?  Or do you also see a bug in Director?

**Comment by mauricefallon** [comment]
scratch that. just checked. nevermind

**Comment by patmarion** [comment]
sorry @maddog-tri, didn't have a chance to get to it today.  I'll let you know.

**Comment by maddog-tri** [comment]
Oh, no rush at all --- I'm not blocked on this (...until someone says "WE NEED A DEMO VIDEO FROM THAT CAR'S POV! RIGHT NOW!").
