### ISSUE TITLE
16.04 binaries

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/director#407]
The Travis CI people suggest using docker containers inside Travis as a way to run 16.04 apps. @patmarion does that seem like a reasonable way to auto-generate the 16.04 binaries?

**Comment by rdeits** [comment]
https://github.com/travis-ci/travis-ci/issues/5821

**Comment by patmarion** [comment]
Sounds possible.  Have you done anything like it before?  I did a quick google search to find projects on github using travis-ci + docker + ubuntu16, and found several, but I don't have time to read more about it right now.

**Comment by rdeits** [comment]
Nope, never done it before. I'm giving it a shot over in #408
