### ISSUE TITLE
Compile error with VTK 7 and PCL enabled due to build errors in PointCloudLibraryPlugin

### ISSUE THREAD

**Issue by gizatt** [RobotLocomotion/director#524]
To be specific, build errors arise in `PointCloudLibraryPlugin`, e.g.
```
threshold->SetInput(inputCopy);
```
(which I know changed from VTK 5 to VTK 6+).

Just FYI!

**Comment by patmarion** [comment]
I have a branch where i am working on updating the full Director superbuild including PCL to work with upgraded VTK.  In the meantime, non of this is working and you should use the `director/master-vtk5` branch.  See #519 Thanks!

**Comment by gizatt** [comment]
Great, glad it's on the radar! Excited for some VTK 7 features soon.

**Comment by patmarion** [comment]
Yeah, so I've actually had it fully working locally, no issues.  Just a matter of getting things cleaned up and committed, which will happen along with things like: drake cmake build updating to director/master and spartan updating to drake/master, etc.

**Comment by patmarion** [comment]
Fixed here: https://github.com/patmarion/PointCloudLibraryPlugin/pull/1
