### ISSUE TITLE
Capitalization issue in mac packages

### ISSUE THREAD

**Issue by rdeits** [RobotLocomotion/director#532]
This was pointed out in https://github.com/rdeits/DrakeVisualizer.jl/issues/58 but I think it's not Julia-specific. It looks like the packaged libraries are symlinked to a folder named `MacOs/lib`, but that should probably be `MacOS/lib`. The offending line is probably here: https://github.com/RobotLocomotion/director/blob/990c869ae40391135e7dc210c02b151ddf454627/distro/package/make_mac_package.sh#L51

This only shows up on macOS when running with a case-sensitive file system (which is a pretty uncommon configuration).

**Comment by patmarion** [comment]
Oops! Yes it's wrong.  Here are the mac bundle docs:

https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW19
