### ISSUE TITLE
Tag most recent version

### ISSUE THREAD

**Issue by TheCynosure** [RobotLocomotion/director#634]
Hello,
The last tag was done in 2017. Could someone just tag the most recent commit as something like 0.1.1 so that I could use the newest version?

**Comment by jwnimmer-tri** [comment]
@patmarion Would you like to weigh in here?

My specific proposal would be to tag the head of the `master` branch as `0.2.0` and post that to https://github.com/RobotLocomotion/director/releases.

If I don't hear back by 2021-10-05, I'll go that route.

**Comment by jwnimmer-tri** [comment]
Done

https://github.com/RobotLocomotion/director/releases/tag/0.2.0
