### ISSUE TITLE
Mention PyQT dependency.

### ISSUE THREAD

**Issue by TheCynosure** [RobotLocomotion/director#635]
It would be helpful to mention the PyQT is used inside this project. This has a different license than Qt itself and has a pay-to-use commercial license.

**Comment by patmarion** [comment]
Director's dependency is on `PythonQt` which is not the same as `PyQt`.

This is the official PythonQt project:

https://github.com/MeVisLab/pythonqt

Director uses this fork:

https://github.com/commontk/PythonQt

**Comment by TheCynosure** [comment]
My mistake, thanks for the links :).
